version: '3.8'

services:
  kugou-checkin:
    image: twh808/kugoulogin:latest
    container_name: kugou-checkin
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
